# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-FSHP
version:      0.2.3
version_from: lib/Crypt/FSHP.pm
installdirs:  site
requires:
    Carp:                          0
    Digest:                        0
    Digest::SHA:                   0
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
